version: '3'
services:
  w_init:
    build: 
      context: .
      dockerfile: ./docker/init/Dockerfile
    volumes:
      - nacl_data:/nacl
  w_run:
    build: 
      context: .
      dockerfile: ./docker/run/Dockerfile
    volumes:
      - nacl_data:/nacl
  analysis:
    build: 
      context: .
      dockerfile: ./docker/analysis/Dockerfile
    ports:
      - "1337:8888"
    volumes:
      - nacl_data:/nacl
  jupyter_run:
    build: 
      context: .
      dockerfile: ./docker/jupyter_run/Dockerfile
    ports:
      - "1336:8888"
    volumes:
      - jupyter_nacl_data:/nacl
volumes:
  nacl_data:
  jupyter_nacl_data: